"""Run the Spark SQL analysis against the sampled behavior data.

The script expects the sample CSV generated by src/etl/sample_user_behavior.py,
derives the profile table inside Spark SQL, then executes the SQL files stored in ./sql.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

from pyspark.sql import SparkSession
from pyspark.sql.types import LongType, StringType, StructField, StructType


DEFAULT_REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_HDFS_SAMPLE_INPUT = (
  f"hdfs://localhost:9000/user/{os.getenv('HDFS_USER', os.getenv('USER', 'current'))}"
  "/cufe-bdmma2026s/data/processed/user_behavior_sample.csv"
)


def is_local_path(path_text: str) -> bool:
    return "://" not in path_text


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Spark SQL analysis for the Taobao sample.")
    parser.add_argument(
        "--sample-input",
        type=str,
        default=DEFAULT_HDFS_SAMPLE_INPUT,
        help="Sample behavior CSV produced by the ETL script. Defaults to the HDFS upload path.",
    )
    parser.add_argument(
        "--sql-dir",
        type=Path,
        default=DEFAULT_REPO_ROOT / "sql",
        help="Directory containing the Spark SQL files.",
    )
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=DEFAULT_REPO_ROOT / "output" / "sql" / "results",
        help="Directory used to store the SQL outputs.",
    )
    return parser.parse_args()


def load_sql(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_dataframe(df, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    df.coalesce(1).write.mode("overwrite").option("header", True).csv(str(output_dir))


def main() -> None:
    args = parse_args()

    behavior_schema = StructType(
        [
            StructField("user_id", LongType(), True),
            StructField("item_id", LongType(), True),
            StructField("category_id", LongType(), True),
            StructField("behavior_type", StringType(), True),
            StructField("timestamp", LongType(), True),
        ]
    )

    spark = (
        SparkSession.builder.appName("taobao-behavior-sql-analysis")
        .config("spark.sql.session.timeZone", "Asia/Shanghai")
        .getOrCreate()
    )

    try:
        if is_local_path(args.sample_input) and not Path(args.sample_input).exists():
            raise FileNotFoundError(f"Sample input not found: {args.sample_input}")

        behavior_df = spark.read.option("header", True).schema(behavior_schema).csv(args.sample_input)
        behavior_df.createOrReplaceTempView("user_behavior")

        spark.sql(
            """
            CREATE OR REPLACE TEMP VIEW user_profile AS
            WITH user_stats AS (
              SELECT
                user_id,
                COUNT(1) AS total_events,
                SUM(CASE WHEN behavior_type = 'buy' THEN 1 ELSE 0 END) AS buy_events,
                COUNT(DISTINCT date_format(from_unixtime(CAST(timestamp AS BIGINT)), 'yyyy-MM-dd')) AS active_days,
                MIN(CAST(timestamp AS BIGINT)) AS first_timestamp,
                MAX(CAST(timestamp AS BIGINT)) AS last_timestamp
              FROM user_behavior
              GROUP BY user_id
            ),
            category_stats AS (
              SELECT
                user_id,
                category_id,
                COUNT(1) AS category_cnt
              FROM user_behavior
              GROUP BY user_id, category_id
            ),
            favorite_category AS (
              SELECT
                user_id,
                element_at(
                  array_sort(
                    collect_list(named_struct('cnt', category_cnt, 'category_id', category_id))
                  ),
                  -1
                ).category_id AS favorite_category_id
              FROM category_stats
              GROUP BY user_id
            )
            SELECT
              s.user_id,
              s.total_events,
              s.buy_events,
              s.active_days,
              s.first_timestamp,
              s.last_timestamp,
              f.favorite_category_id,
              CASE
                WHEN s.total_events <= 3 THEN 'light'
                WHEN s.total_events <= 10 THEN 'medium'
                ELSE 'heavy'
              END AS user_tier
            FROM user_stats s
            LEFT JOIN favorite_category f
              ON s.user_id = f.user_id
            """
        )

        query_specs = [
            ("01_daily_activity.sql", "01_daily_activity"),
            ("02_top_categories.sql", "02_top_categories"),
            ("03_time_buckets.sql", "03_time_buckets"),
            ("04_user_tier_join.sql", "04_user_tier_join"),
        ]

        args.results_dir.mkdir(parents=True, exist_ok=True)

        for sql_file_name, output_name in query_specs:
            sql_path = args.sql_dir / sql_file_name
            if not sql_path.exists():
                raise FileNotFoundError(f"SQL file not found: {sql_path}")

            result_df = spark.sql(load_sql(sql_path))
            result_df.show(20, truncate=False)
            write_dataframe(result_df, args.results_dir / output_name)
            print(f"Saved result for {sql_file_name} to {args.results_dir / output_name}")
    finally:
        spark.stop()


if __name__ == "__main__":
    main()